name: CI Branch - Roboshop User
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'db/**'
      - '.github/workflows/ci-db-main.yml'

jobs:
  cicd:
    uses: raghudevopsb88/github-reusable-workflows/.github/workflows/ci-b.yml@main
